spring.application.name=ai-support-hub
server.port=8000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.model.embedding.text=google-genai
spring.ai.google.genai.embedding.text.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.task-type=RETRIEVAL_DOCUMENT

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=${ORACLE_USERNAME}
spring.datasource.password=${ORACLE_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.ai.vectorstore.oracle.initialize-schema=true
spring.ai.vectorstore.oracle.remove-existing-vector-store-table=true
spring.ai.vectorstore.oracle.dimensions=3072
spring.ai.vectorstore.oracle.distance-type=COSINE
spring.ai.vectorstore.oracle.index-type=IVF

#app.ai.system-prompt=You are a helpful technical assistant. Explain concepts clearly and use simple examples.