-- ============================================================
-- AI SUPPORT HUB
-- Oracle AI Database 26ai Free
-- Schema: AIUSER
-- ============================================================

SET SERVEROUTPUT ON;

-- ============================================================
-- 1. SUPPORT CLIENTS
-- Tenant/client registration and API key authentication
-- ============================================================

CREATE TABLE SUPPORT_CLIENTS (
                                 ID              NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                 CLIENT_KEY      VARCHAR2(100) NOT NULL,
                                 NAME            VARCHAR2(200) NOT NULL,
                                 API_KEY_HASH    VARCHAR2(255) NOT NULL,
                                 ACTIVE          NUMBER(1) DEFAULT 1 NOT NULL,
                                 CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 UPDATED_AT      TIMESTAMP,

                                 CONSTRAINT PK_SUPPORT_CLIENTS PRIMARY KEY (ID),
                                 CONSTRAINT UK_SUPPORT_CLIENTS_KEY UNIQUE (CLIENT_KEY),
                                 CONSTRAINT CK_SUPPORT_CLIENTS_ACTIVE CHECK (ACTIVE IN (0, 1))
);

-- ============================================================
-- 2. SUPPORT AGENTS
-- Agent accounts belonging to a client
-- ============================================================

CREATE TABLE SUPPORT_AGENTS (
                                ID              NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                CLIENT_ID       NUMBER NOT NULL,
                                USERNAME        VARCHAR2(100) NOT NULL,
                                PASSWORD_HASH   VARCHAR2(255) NOT NULL,
                                ROLE            VARCHAR2(50) NOT NULL,
                                ACTIVE          NUMBER(1) DEFAULT 1 NOT NULL,
                                CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                UPDATED_AT      TIMESTAMP,

                                CONSTRAINT PK_SUPPORT_AGENTS PRIMARY KEY (ID),
                                CONSTRAINT FK_AGENTS_CLIENT FOREIGN KEY (CLIENT_ID)
                                    REFERENCES SUPPORT_CLIENTS(ID),
                                CONSTRAINT UK_AGENT_CLIENT_USERNAME
                                    UNIQUE (CLIENT_ID, USERNAME),
                                CONSTRAINT CK_AGENTS_ACTIVE CHECK (ACTIVE IN (0, 1))
);

-- ============================================================
-- 3. SUPPORT CONVERSATIONS
-- Customer conversation metadata
-- ============================================================

CREATE TABLE SUPPORT_CONVERSATIONS (
                                       ID              NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                       CLIENT_ID       NUMBER NOT NULL,
                                       CUSTOMER_ID     VARCHAR2(200) NOT NULL,
                                       CONVERSATION_ID VARCHAR2(200) NOT NULL,
                                       STATUS          VARCHAR2(30) DEFAULT 'OPEN' NOT NULL,
                                       CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                       UPDATED_AT      TIMESTAMP,

                                       CONSTRAINT PK_SUPPORT_CONVERSATIONS PRIMARY KEY (ID),
                                       CONSTRAINT FK_CONVERSATIONS_CLIENT FOREIGN KEY (CLIENT_ID)
                                           REFERENCES SUPPORT_CLIENTS(ID),
                                       CONSTRAINT UK_CLIENT_CONVERSATION
                                           UNIQUE (CLIENT_ID, CONVERSATION_ID)
);

-- ============================================================
-- 4. SUPPORT MESSAGES
-- Conversation message history
-- ============================================================

CREATE TABLE SUPPORT_MESSAGES (
                                  ID              NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                  CONVERSATION_ID NUMBER NOT NULL,
                                  SENDER_TYPE     VARCHAR2(30) NOT NULL,
                                  CONTENT         CLOB NOT NULL,
                                  CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                                  CONSTRAINT PK_SUPPORT_MESSAGES PRIMARY KEY (ID),
                                  CONSTRAINT FK_MESSAGES_CONVERSATION
                                      FOREIGN KEY (CONVERSATION_ID)
                                          REFERENCES SUPPORT_CONVERSATIONS(ID)
);

-- ============================================================
-- 5. ACTION APPROVALS
-- Human approval for sensitive agent actions
-- ============================================================

CREATE TABLE ACTION_APPROVALS (
                                  ID              NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                  CLIENT_ID       NUMBER NOT NULL,
                                  CONVERSATION_ID NUMBER,
                                  ACTION_TYPE     VARCHAR2(100) NOT NULL,
                                  ACTION_PAYLOAD  CLOB,
                                  STATUS          VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
                                  APPROVED_BY     VARCHAR2(200),
                                  CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                  UPDATED_AT      TIMESTAMP,

                                  CONSTRAINT PK_ACTION_APPROVALS PRIMARY KEY (ID),
                                  CONSTRAINT FK_APPROVALS_CLIENT FOREIGN KEY (CLIENT_ID)
                                      REFERENCES SUPPORT_CLIENTS(ID),
                                  CONSTRAINT FK_APPROVALS_CONVERSATION
                                      FOREIGN KEY (CONVERSATION_ID)
                                          REFERENCES SUPPORT_CONVERSATIONS(ID)
);

-- ============================================================
-- 6. KNOWLEDGE DOCUMENTS
-- Metadata for uploaded/ingested knowledge sources
-- ============================================================

CREATE TABLE KNOWLEDGE_DOCUMENTS (
                                     ID              NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                     CLIENT_ID       NUMBER NOT NULL,
                                     DOCUMENT_NAME   VARCHAR2(500) NOT NULL,
                                     SOURCE          VARCHAR2(1000),
                                     CONTENT_TYPE    VARCHAR2(100),
                                     STATUS          VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
                                     CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                     UPDATED_AT      TIMESTAMP,

                                     CONSTRAINT PK_KNOWLEDGE_DOCUMENTS PRIMARY KEY (ID),
                                     CONSTRAINT FK_DOCUMENTS_CLIENT FOREIGN KEY (CLIENT_ID)
                                         REFERENCES SUPPORT_CLIENTS(ID)
);

-- ============================================================
-- 7. AUDIT LOGS
-- Administrative and security activity
-- ============================================================

CREATE TABLE AUDIT_LOGS (
                            ID              NUMBER GENERATED BY DEFAULT AS IDENTITY,
                            CLIENT_ID       NUMBER,
                            ACTOR            VARCHAR2(200),
                            ACTION           VARCHAR2(200) NOT NULL,
                            DETAILS          CLOB,
                            CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                            CONSTRAINT PK_AUDIT_LOGS PRIMARY KEY (ID),
                            CONSTRAINT FK_AUDIT_CLIENT FOREIGN KEY (CLIENT_ID)
                                REFERENCES SUPPORT_CLIENTS(ID)
);

-- ============================================================
-- 8. INDEXES
-- ============================================================

CREATE INDEX IDX_AGENTS_CLIENT
    ON SUPPORT_AGENTS(CLIENT_ID);

CREATE INDEX IDX_CONVERSATIONS_CLIENT
    ON SUPPORT_CONVERSATIONS(CLIENT_ID);

CREATE INDEX IDX_MESSAGES_CONVERSATION
    ON SUPPORT_MESSAGES(CONVERSATION_ID);

CREATE INDEX IDX_APPROVALS_CLIENT_STATUS
    ON ACTION_APPROVALS(CLIENT_ID, STATUS);

CREATE INDEX IDX_DOCUMENTS_CLIENT_STATUS
    ON KNOWLEDGE_DOCUMENTS(CLIENT_ID, STATUS);

CREATE INDEX IDX_AUDIT_CLIENT_CREATED
    ON AUDIT_LOGS(CLIENT_ID, CREATED_AT);

COMMIT;

-- ============================================================
-- 9. VERIFY CREATED TABLES
-- ============================================================

SELECT TABLE_NAME
FROM USER_TABLES
ORDER BY TABLE_NAME;

PROMPT AI Support Hub schema script completed.